@extends('layouts.app')

@section('title', 'Create Transaction')

@section('content')
<div class="page-header">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-3">
        <div>
            <h2><i class="bi bi-plus-circle me-2"></i>Create New Transaction</h2>
            <p class="text-muted mb-0">Fill in the details to create a new payment transaction</p>
        </div>
        <a href="{{ route('user.transactions.index') }}" class="btn btn-outline-secondary">
            <i class="bi bi-arrow-left me-2"></i>Back
        </a>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <form id="transactionForm">
            @csrf
            
            <!-- Basic Information Section -->
            <div class="mb-4">
                <h5 class="mb-3 pb-2 border-bottom">
                    <i class="bi bi-info-circle me-2 text-primary"></i>Basic Information
                </h5>
                <div class="row g-3">
                    <div class="col-12">
                        <label class="form-label fw-semibold">
                            <i class="bi bi-file-text me-1"></i>Order Description <span class="text-danger">*</span>
                        </label>
                        <input type="text" name="order_desc" class="form-control" placeholder="Enter order description" required>
                        <small class="text-muted">Merchant Order ID will be automatically generated by the system</small>
                    </div>
                </div>
                <div class="row g-3 mt-2">
                    <div class="col-12 col-md-4">
                        <label class="form-label fw-semibold">
                            <i class="bi bi-currency-dollar me-1"></i>Amount <span class="text-danger">*</span>
                        </label>
                        <input type="text" name="amount" class="form-control" placeholder="0.00" required>
                    </div>
                    <div class="col-12 col-md-4">
                        <label class="form-label fw-semibold">
                            <i class="bi bi-globe me-1"></i>Currency <span class="text-danger">*</span>
                        </label>
                        <input type="text" name="currency" class="form-control" value="EUR" readonly>
                        <small class="text-muted">EUR (Euro) is the only supported currency</small>
                    </div>
                        <div class="col-12 col-md-4">
                        <label class="form-label fw-semibold">
                            <i class="bi bi-credit-card me-1"></i>Payment Method <span class="text-danger">*</span>
                        </label>
                        <input type="text" name="pay_method" id="pay_method" class="form-control" value="SEPA" readonly>
                        <small class="text-muted">SEPA is the only supported payment method</small>
                    </div>
                </div>
            </div>

            <!-- Customer Information Section -->
            <div class="mb-4">
                <h5 class="mb-3 pb-2 border-bottom">
                    <i class="bi bi-person me-2 text-success"></i>Customer Information
                </h5>
                <div class="row g-3">
                    <div class="col-12 col-md-6">
                        <label class="form-label fw-semibold">
                            <i class="bi bi-envelope me-1"></i>Customer Email <span class="text-danger">*</span>
                        </label>
                        <input type="email" name="customer_email" id="customer_email" class="form-control" value="{{ auth()->user()->email }}" readonly>
                        <small class="text-muted">Your email address will be used for this transaction.</small>
                    </div>
                </div>
            </div>

            <!-- Requisites Section -->
            <div class="mb-4">
                <h5 class="mb-3 pb-2 border-bottom">
                    <i class="bi bi-bank me-2 text-warning"></i>Payment Requisites (SEPA)
                </h5>
                <div id="sepa-requisites">
                    <div class="row g-3 mb-3">
                        <div class="col-12 col-md-6">
                            <label class="form-label fw-semibold">
                                <i class="bi bi-123 me-1"></i>Account Number <span class="text-danger">*</span>
                            </label>
                            <input type="text" name="requisites[account_number]" class="form-control" placeholder="Enter account number" required>
                        </div>
                        <div class="col-12 col-md-6">
                            <label class="form-label fw-semibold">
                                <i class="bi bi-person me-1"></i>Account Name <span class="text-danger">*</span>
                            </label>
                            <input type="text" name="requisites[account_name]" class="form-control" placeholder="Enter account holder name" required>
                        </div>
                    </div>
                    <div class="row g-3 mb-3">
                        <div class="col-12 col-md-6">
                            <label class="form-label fw-semibold">
                                <i class="bi bi-person me-1"></i>First Name <span class="text-danger">*</span>
                            </label>
                            <input type="text" name="requisites[customer][first_name]" class="form-control" placeholder="Enter first name" required>
                        </div>
                        <div class="col-12 col-md-6">
                            <label class="form-label fw-semibold">
                                <i class="bi bi-person me-1"></i>Last Name <span class="text-danger">*</span>
                            </label>
                            <input type="text" name="requisites[customer][last_name]" class="form-control" placeholder="Enter last name" required>
                        </div>
                    </div>
                    <div class="row g-3">
                        <div class="col-12 col-md-6">
                            <label class="form-label fw-semibold">
                                <i class="bi bi-globe me-1"></i>Country <span class="text-danger">*</span>
                            </label>
                            <select name="requisites[customer][address][country]" class="form-select" required>
                                <option value="">Select Country</option>
                                <option value="GB">United Kingdom (GB)</option>
                                <option value="US">United States (US)</option>
                                <option value="IT">Italy (IT)</option>
                                <option value="DE">Germany (DE)</option>
                                <option value="FR">France (FR)</option>
                                <option value="ES">Spain (ES)</option>
                                <option value="NL">Netherlands (NL)</option>
                                <option value="BE">Belgium (BE)</option>
                                <option value="AT">Austria (AT)</option>
                                <option value="PT">Portugal (PT)</option>
                                <option value="IE">Ireland (IE)</option>
                                <option value="LU">Luxembourg (LU)</option>
                                <option value="FI">Finland (FI)</option>
                                <option value="GR">Greece (GR)</option>
                                <option value="PL">Poland (PL)</option>
                                <option value="CZ">Czech Republic (CZ)</option>
                                <option value="SE">Sweden (SE)</option>
                                <option value="DK">Denmark (DK)</option>
                                <option value="NO">Norway (NO)</option>
                                <option value="CH">Switzerland (CH)</option>
                            </select>
                            <small class="text-muted">Must be a valid 2-letter ISO country code</small>
                        </div>
                        <div class="col-12 col-md-6">
                            <label class="form-label fw-semibold">
                                <i class="bi bi-geo-alt me-1"></i>Address <span class="text-danger">*</span>
                            </label>
                            <input type="text" name="requisites[customer][address][address1]" class="form-control" placeholder="Enter street address" required>
                        </div>
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-end gap-2 mt-4 pt-3 border-top">
                <a href="{{ route('user.transactions.index') }}" class="btn btn-outline-secondary">
                    <i class="bi bi-x-circle me-2"></i>Cancel
                </a>
                <button type="submit" class="btn btn-primary" id="submitBtn">
                    <i class="bi bi-check-circle me-2"></i>Create Transaction
                </button>
            </div>
        </form>
    </div>
</div>

@push('scripts')
<script>
$(document).ready(function() {
    $('#transactionForm').on('submit', function(e) {
        e.preventDefault();
        
        // Build form data object
        // Note: merchant_order_id is now generated on the backend
        const formData = {
            order_desc: $('input[name="order_desc"]').val(),
            amount: $('input[name="amount"]').val(),
            currency: 'EUR', // Fixed to EUR
            pay_method: 'sepa', // Fixed to SEPA
            customer_email: $('input[name="customer_email"]').val(), // Customer email
            requisites: {
                account_number: $('input[name="requisites[account_number]"]').val(),
                account_name: $('input[name="requisites[account_name]"]').val(),
                customer: {
                    first_name: $('input[name="requisites[customer][first_name]"]').val(),
                    last_name: $('input[name="requisites[customer][last_name]"]').val(),
                    address: {
                        country: $('select[name="requisites[customer][address][country]"]').val().toUpperCase(),
                        address1: $('input[name="requisites[customer][address][address1]"]').val()
                    }
                }
            }
        };

        // Note: Customer ID and IP address are automatically set on the backend
        // User will be found or created based on the email provided

        const btn = $('#submitBtn');
        const originalHtml = btn.html();
        btn.prop('disabled', true).html('<span class="spinner-border spinner-border-sm me-2"></span>Processing...');

        $.ajax({
            url: '{{ route("user.transactions.store") }}',
            method: 'POST',
            data: JSON.stringify(formData),
            contentType: 'application/json',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            success: function(response) {
                if (response.success) {
                    window.location.href = '{{ route("user.transactions.index") }}';
                } else {
                    alert('Error: ' + (response.message || 'Unknown error'));
                    btn.prop('disabled', false).html(originalHtml);
                }
            },
            error: function(xhr) {
                const error = xhr.responseJSON?.message || 'An error occurred';
                alert('Error: ' + error);
                btn.prop('disabled', false).html(originalHtml);
            }
        });
    });
});
</script>
@endpush
@endsection
